server:
  port: 9090
  
# tag::securityCreds[]
spring:
  security:
    user:
      name: ${TACOCLOUD_ADMIN_USERNAME:admin}
      password: ${TACOCLOUD_ADMIN_PASSWORD:${random.uuid}}
# end::securityCreds[]
